project:
  type: website
  output-dir: docs

website:
  title: "Kodjo Aklobessi"
  navbar:
    pinned: true
    collapse-after: 3
    left:
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/kaklobessi
        aria-label: GitHub
      - icon: envelope
        href: mailto:kodjo.aklobessi@umontreal.ca
        aria-label: Email
  page-footer:
    left: "© 2026 Kodjo Aklobessi"
    right: "PhD Candidate, Université de Montréal"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
